import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
const source=fileURLToPath(new URL('../../scripts/ops/Invoke-AurumCommand.ps1',import.meta.url));
const windows=process.platform==='win32';
async function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'commander-client-'));const workspace=path.join(root,'workspace');fs.mkdirSync(workspace);const token='synthetic_fixture_token_0123456789';const tokenFile=path.join(root,'token');fs.writeFileSync(tokenFile,token);let requests=0;let mode='ok';
 const server=http.createServer(async(req,res)=>{requests++;let text='';for await(const b of req)text+=b;const body=JSON.parse(text);if(mode==='redirect'){res.writeHead(302,{location:'http://127.0.0.1:1/steal'});res.end();return;}assert.equal(req.headers.authorization,'Bearer '+token);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,exitCode:0,timedOut:false,stdout:'fixture-ok',receipt:{schema:'aurum.commander.receipt.v1',ok:true,operationId:mode==='wrong-id'?'wrong':body.operationId}}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});});const cfg={schema:'aurum.commander.install.v1',workspace,tokenFile,port:server.address().port};const config=path.join(root,'config.json');const harness=path.join(root,'test.ps1');fs.writeFileSync(harness,`param([string]$ConfigPath)\n. '${source.replaceAll("'","''")}'\ntry { $r=Invoke-AurumCommand -ConfigPath $ConfigPath -Body @{action='run';commandId='node';args=@('--version');timeoutMs=1000;operationId='client-test'};Write-Output $r.stdout;exit 0 } catch { Write-Output $_.Exception.Message;exit 1 }\n`);
 return {cfg,root,tokenFile,setMode:v=>mode=v,getRequests:()=>requests,run:async()=>{fs.writeFileSync(config,JSON.stringify(cfg));return await new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','RemoteSigned','-File',harness,'-ConfigPath',config],{windowsHide:true,stdio:['ignore','pipe','pipe']});let text='';p.stdout.on('data',b=>text+=b);p.stderr.on('data',b=>text+=b);p.on('error',reject);p.on('close',code=>resolve({code,text}));});}};
}
test('client uses protected installed config while old workspace token is absent',{skip:!windows},async t=>{const f=await fixture(t);assert.equal((await f.run()).code,0);assert(!fs.existsSync(path.join(f.cfg.workspace,'.aurum-token')));assert.equal(fs.readFileSync(f.tokenFile,'utf8'),'synthetic_fixture_token_0123456789');});
test('client refuses nonlocal host before any HTTP request',{skip:!windows},async t=>{const f=await fixture(t);f.cfg.host='evil.example';assert.equal((await f.run()).code,1);assert.equal(f.getRequests(),0);});
test('client rejects token placed in command workspace',{skip:!windows},async t=>{const f=await fixture(t);f.cfg.tokenFile=path.join(f.cfg.workspace,'token');fs.writeFileSync(f.cfg.tokenFile,'synthetic_fixture_token_0123456789');assert.equal((await f.run()).code,1);assert.equal(f.getRequests(),0);});
test('client sanitizes failures and refuses malformed credential',{skip:!windows},async t=>{const f=await fixture(t);fs.writeFileSync(f.tokenFile,'PRIVATE_SECRET\nINJECT');const r=await f.run();assert.equal(r.code,1);assert(!r.text.includes('PRIVATE_SECRET'));assert.equal(f.getRequests(),0);});
test('client refuses redirects without retrying',{skip:!windows},async t=>{const f=await fixture(t);f.setMode('redirect');assert.equal((await f.run()).code,1);assert.equal(f.getRequests(),1);});
test('client rejects unrelated execution receipt',{skip:!windows},async t=>{const f=await fixture(t);f.setMode('wrong-id');assert.equal((await f.run()).code,1);});
