import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {normalizeJob} from '../../factory/workflow-controller.mjs';import {projectRecords,readSnapshot,createDashboardServer} from '../../factory/dashboard-feed.mjs';
const now=Date.now();
function record(){const job=normalizeJob({id:'example-job',goal:'SECRET_GOAL_DO_NOT_EXPORT',kind:'test',scope:'/private/path',revision:'v1',classification:'synthetic',checkinMinutes:[1,2]});return {schema:'factory.execution-record.v1',job,status:'succeeded',reason:'separate_verification_passed',events:[{at:new Date(now).toISOString()}],attempts:1,result:{exitCode:0,jobFingerprint:job.fingerprint,executorId:'process',artifactDigest:'a'.repeat(64),token:'SECRET_TOKEN_DO_NOT_EXPORT'},verification:{passed:true,jobFingerprint:job.fingerprint,verifierId:'reader',artifactDigest:'a'.repeat(64)}};}
test('fresh independently matched receipts count as verified',()=>{assert.equal(projectRecords([record()],{now}).totals.succeeded,1);});
test('old successes become stale, not current green',()=>{assert.equal(projectRecords([record()],{now:now+900001}).totals.stale,1);});
test('self-reported success is explicitly unverified',()=>{const r=record();delete r.verification;assert.equal(projectRecords([r],{now}).totals.unverified,1);});
test('mismatched verifier digest cannot count as success',()=>{const r=record();r.verification.artifactDigest='b'.repeat(64);assert.equal(projectRecords([r],{now}).totals.unverified,1);});
test('duplicate job receipts are removed instead of double-counted',()=>{const x=projectRecords([record(),record()],{now});assert.equal(x.jobs.length,0);assert(x.errors.includes('duplicate-job'));});
test('future timestamps and malformed evidence do not become healthy',()=>{const r=record();r.events[0].at=new Date(now+60000).toISOString();assert.equal(projectRecords([r],{now}).totals.stale,1);assert.equal(projectRecords([{}],{now}).errors.length,1);});
test('projection strips goals, paths, tokens and unknown reason text',()=>{const r=record();r.reason='SECRET_REASON';const s=JSON.stringify(projectRecords([r],{now}));assert(!s.includes('SECRET'));assert(!s.includes('/private/path'));});
test('missing data is surfaced, not fabricated',()=>{const s=readSnapshot({recordsRoot:'/definitely-not-here',providerFile:'/not-here',now});assert.equal(s.jobEvidence.totals.succeeded,0);assert.equal(s.errors.length,2);});
test('expired provider canary does not count as live capacity',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'feed-'));try{const p=path.join(root,'providers.json');fs.writeFileSync(p,JSON.stringify({schema:'factory.free-capacity.state.v1',generatedAt:new Date(now-1000000).toISOString(),providers:[{admitted:true,evidence:{ok:true,reportedCost:0,paidFallbackUsed:false,checkedAt:new Date(now-1000000).toISOString()}}]}));const records=path.join(root,'records');fs.mkdirSync(records);const s=readSnapshot({recordsRoot:records,providerFile:p,now});assert.equal(s.providers.freshVerified,0);assert.equal(s.providers.stale,1);}finally{fs.rmSync(root,{recursive:true,force:true});}});
function request(port,method,url,headers={}){return new Promise((resolve,reject)=>{const r=http.request({hostname:'127.0.0.1',port,method,path:url,headers},res=>{let body='';res.on('data',b=>body+=b);res.on('end',()=>resolve({status:res.statusCode,body,headers:res.headers}));});r.on('error',reject);r.end();});}
test('HTTP feed is loopback-only, read-only, no arbitrary paths or cross-origin access',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'feed-http-'));const app=createDashboardServer({recordsRoot:root,providerFile:path.join(root,'none'),port:0,probeServices:false});try{const a=await app.listen();assert.equal(a.address,'127.0.0.1');assert.equal((await request(a.port,'GET','/v1/snapshot')).status,200);assert.equal((await request(a.port,'POST','/v1/snapshot')).status,405);assert.equal((await request(a.port,'GET','/state/auth-token')).status,404);assert.equal((await request(a.port,'GET','/v1/snapshot?file=secret')).status,404);assert.equal((await request(a.port,'GET','/',{Host:'evil.test'})).status,403);assert.equal((await request(a.port,'GET','/',{Origin:'https://evil.test'})).status,403);const page=await request(a.port,'GET','/');assert.equal(page.status,200);assert(page.headers['content-security-policy'].includes("script-src 'self'"));assert(page.body.includes('READ ONLY'));}finally{await app.close();fs.rmSync(root,{recursive:true,force:true});}});
